module.exports = {
    ENCRYPTION_ERROR_MESSAGE : "An error occurred during encryption. Please try again.",
    DECRYPTION_ERROR_MESSAGE : "An error occurred during decryption. Please try again.",
    PROTOCOL_CONNECTION_LOST : "Database connection was closed. Please try again.",
    ER_CON_COUNT_ERROR       : "The database has too many connections. Please try again.",
    ECONNREFUSED             : "Database connection was refused. Please try again.",
    SERVER_UP                : "Server is up and running.",
    SERVER_CHECK_FAIL        : "Couldn't read server status. Please try again.",
    UPLOAD_SUCCESS           : "File uploaded successfully.",
    UPLOAD_FAIL              : "Failed to upload the file. Please try again.",
    EMAIL_OR_PASS_INCORRECT  : "The provided email or password is incorrect.",
    INTERNAL_ERR             : "Internal server error. Please try again later.",
    USERNAME_EXISTS          : "A user with the same email ID or username already exists.",
    SIGNUP_SUCCESS           : "User has been registered successfully."
}
